#!/usr/bin/env bash
#
# Description: reshelves a p4 shelved changelist
#              deletes the current shevlve of a p4 changelist and
#              shelves the current pending changelist.
# Author: Arnon Zilca
#

set -e

# get script dir path
SCRIPT_PATH="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd)"

source "${SCRIPT_PATH}/p4-help-functions"

usage() {
    echo "$(basename $0) -- deletes the current shevlve of a p4 changelist and" >&2
    echo "    shelves the current pending changelist." >&2
    echo "usage: $(basename $0) shelved-changelist" >&2
}

if [[ "$1" == "-h" ]]; then
    usage
    exit 0
fi

if [[ $# -ne 1 ]]; then
    changelist=$(p4-pick-changelist "reshelve" 0 -d) # sourced in p4-help-functions
else
    changelist="$1"
fi

p4 shelve -d -c "${changelist}"
echo -n "Re"
p4 shelve -c "${changelist}"
