#!/bin/bash
#
# Description: finds untracked (unadded) files in a p4 dir
# Author: Arnon Zilca
#

set -e

source "p4-help-functions"

usage() {
    echo "$(basename $0) -- finds untracked (unadded) files in a p4 dir" >&2
    echo "usage: $(basename $0) [options] [dir]" >&2
    echo    "  -d   search depth (default is unlimited)" >&2
}

while getopts "h?d:" opt; do
    case "${opt}" in
        h)
            usage
            exit 0
            ;;
        d)
            MAX_DEPTH="-maxdepth ${OPTARG}"
            ;;
        *)
            usage
            exit 1
            ;;
    esac
done
shift $(( OPTIND - 1 ))

DIR="$1"

if [[ -z "${DIR}" ]]; then
    DIR="."
fi

find "${DIR}" ${MAX_DEPTH} -type f -print0 | xargs -0 p4 fstat >/dev/null
