#!/bin/bash
#
# Description: unshelves a p4 changelist to its own changelist
# Author: Arnon Zilca
#

set -e

source "p4-help-functions"

usage() {
    echo "$(basename $0) -- unshelves a p4 changelist to its own changelist" >&2
    echo "usage: $(basename $0) shelved-changelist" >&2
}

if [[ "$1" == "-h" ]]; then
    usage
    exit 0
fi

if [[ $# -ne 1 ]]; then
    changelist=$(p4-pick-changelist "unshelve") # sourced in p4-help-functions
else
    changelist="$1"
fi

p4 unshelve -s "${changelist}" -c "${changelist}"
